---
title: "rainfall_analysis"
output: html_document
date: "2024-03-07"
---
```{r}
library(tidyverse)
library(ggplot2)
library(gganimate)
```


```{r}
RainfallKerala <- read_csv("~/Desktop/DATA450Spring24/Rainfall_Data/RainfallKerala.csv")
head(RainfallKerala)
```

```{r}
animation<- RainfallKerala %>%
  group_by(Year) %>%
  mutate(
    rank = as.numeric(row_number(Rainfall))
  )

```
```{r}
animatedPlot <- animation%>%ggplot() +
  geom_col(
    mapping = aes(
      x = rank,
      y = Rainfall,
      fill = as.factor(Month)
    ),
    width = 0.9,
    alpha = 1
  ) +
  geom_text(
    mapping = aes(
      x = rank,
      y = 0,
      label = Month
    ),
    vjust = 0.2,
    hjust = 1
  ) +
  geom_text(
    mapping = aes(
      x = rank,
      y = Rainfall,
      label = as.factor(Rainfall)
    ),
    vjust = 0.2,
    hjust = 0
  ) +
  coord_flip(
    clip = "off",
    expand = FALSE,
    xlim = c(0.5, 12.5)
  ) +
  scale_y_continuous(labels = scales::comma) +
  guides(color = FALSE, fill = FALSE) +
  labs(title = "{closest_state}", x = "", y = "Rainfall (mm)") +
  theme(
    plot.title = element_text(hjust = 0.5, size = 32),
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(),
    plot.margin = margin(1, 3, 1, 4, "cm")
  ) +
  transition_states(Year, transition_length = 4, state_length = 1) +#0.01
  ease_aes("cubic-in-out")


```


```{r}
animate(animatedPlot, fps = 5,nframes = 700)
```

```{r}

```



